[[DeliveryPlace-API]]
== Delivery Place API

=== 배달 가능 지역 추가
`POST /owner/delivery-place/shop/{shopId}/add`

operation::delivery-place/add[snippets='http-request,http-response,request-headers,path-parameters,request-fields,response-fields']

=== 배달 가능 지역 삭제
`DELETE /owner/delivery-place/{deliveryPlaceId}/delete`

operation::delivery-place/delete[snippets='http-request,http-response,request-headers,path-parameters']

=== 배달 요금 수정
`PATCH /owner/delivery-place/{deliveryPlaceId}/delivery-price/update`

operation::delivery-place/update-delivery-price[snippets='http-request,http-response,request-headers,path-parameters,request-fields']

=== 배달 요금 일괄 수정
`PATCH /owner/delivery-place/shop/{shopId}/delivery-price/update`

operation::delivery-place/update-all-delivery-price[snippets='http-request,http-response,request-headers,path-parameters,request-fields']

=== 배달 요금 조회
`GET /owner/delivery-place/{deliveryPlaceId}/delivery-price`

operation::delivery-place/get-delivery-price[snippets='http-request,http-response,path-parameters,response-fields']

=== 배달 요금 인상/인하
`PATCH /owner/delivery-place/shop/{shop id}/delivery-price/adjustment`

operation::delivery-place/adjustment-delivery-price[snippets='http-request,http-response,path-parameters,request-fields']

=== 주문 요금 인상/인하
`PATCH /owner/delivery-place/shop/{shop id}/order-price/adjustment`

operation::delivery-place/adjustment-order-price[snippets='http-request,http-response,path-parameters,request-fields']