[[Member-API]]
== Member API

[[Member-join]]
=== 멤버 회원가입
`POST /member/join`

operation::member/join[snippets='http-request,http-response,request-fields,response-fields']

[[Member-default-login]]
=== 멤버 기본 로그인
`POST /member/login`

operation::default/login[snippets='http-request,http-response,request-fields,response-fields,response-headers']

[[Member-social-login]]
=== 멤버 소셜 로그인
`POST /member/login`

operation::social/login[snippets='http-request,http-response,request-fields,response-fields,response-headers']

[[Member-logout]]
=== 멤버 로그아웃
`POST /member/logout/{memberId}`

operation::default/logout[snippets='http-request,http-response,request-headers,path-parameters,response-headers']

[[Member-reissue]]
=== 멤버 리프레시 토큰 재발급
`POST /re-issue`

operation::member/re-issue[snippets='http-request,http-response,response-headers,response-body']

[[Member-mypage]]
=== 멤버 마이페이지 조회
`GET /member/mypage`

operation::member/mypage[snippets='http-request,http-response,request-headers,response-fields']

[[Member-update]]
=== 멤버 회원정보 수정
`PATCH /member/update`

operation::member/update[snippets='http-request,http-response,request-headers,request-fields']

[[Member-delete]]
=== 멤버삭제
`DELETE /member/delete`

operation::member/delete[snippets='http-request,http-response,request-headers']