[[MenuOptionGroup-API]]
== Menu Option Group API

[[Option-Group]]
=== 옵션 그룹 추가
`POST /owner/menu-option-group/shop/{shop id}/add`

operation::menu-option-group/add-group[snippets='http-request,http-response,request-headers,path-parameters,request-fields,response-fields']

=== 옵션 그룹 조회
`GET /owner/menu-option-group/{menu option group id`

operation::menu-option-group/find-one[snippets='http-request,http-response,path-parameters,response-fields']

=== 옵션 그룹 전체 조회
`GET /owner/menu-option-group/shop/{shop id}`

operation::menu-option-group/find-all[snippets='http-request,http-response,path-parameters,response-fields']

=== 옵션 그룹 수정
`PATCH /owner/menu-option-group/{menu option group id}/update`

operation::menu-option-group/update[snippets='http-request,http-response,request-headers,path-parameters,request-fields']

=== 옵션 그룹 삭제
`DELETE /owner/menu-option-group/{menu option group id}/delete`

operation::menu-option-group/delete[snippets='http-request,http-response,request-headers,path-parameters']

=== 옵션 그룹 메뉴 연결
`PUT /owner/menu-option-group/{menu option group id}/link-menu`

operation::menu-option-group/link-menu[snippets='http-request,http-response,request-headers,path-parameters,request-fields']

=== 옵션 그룹 정렬 순서 변경
`PUT /owner/menu-option-group/shop/{shop id}/change-position`

operation::menu-option-group/change-position[snippets='http-request,http-response,request-headers,path-parameters,request-fields']

=== 옵션 그룹 노출 상태 설정
`PATCH /owner/menu-option-group/{menu option group id}/visible`

operation::menu-option-group/update-visible[snippets='http-request,http-response,path-parameters,request-fields']

[[Option]]
=== 옵션 추가
`POST /owner/menu-option-group/{menu option group id}/add-option`

operation::menu-option-group/add-option[snippets='http-request,http-response,request-headers,path-parameters,request-fields,response-fields']

=== 옵션 조회
`GET /owner/menu-option-group/option/{menu option id}`

operation::menu-option-group/find-option[snippets='http-request,http-response,path-parameters,response-fields']

=== 옵션 수정
`PATCH /owner/menu-option-group/option/{menu option id}/update`

operation::menu-option-group/update-option[snippets='http-request,http-response,request-headers,path-parameters,request-fields']

=== 옵션 삭제
`DELETE /owner/menu-option-group/option/{menu option id}/delete`

operation::menu-option-group/delete-option[snippets='http-request,http-response,request-headers,path-parameters']

=== 옵션 정렬 순서 변경
`PUT /owner/menu-option-group/{menu option group id}/change-option-position`

operation::menu-option-group/change-option-position[snippets='http-request,http-response,request-headers,path-parameters,request-fields']

=== 옵션 노출 상태 설정
`PATCH /owner/menu-option-group/option/{menu option id}/visible`

operation::menu-option-group/update-option-visible[snippets='http-request,http-response,path-parameters,request-fields']
