[[MenuOptionGroup-API]]
== Menu Option Group API

[[Option-Group]]
=== 옵션 그룹 추가
operation::menu-option-group/add-group[snippets='http-request,http-response,request-headers,path-parameters,request-fields,response-fields']

=== 옵션 그룹 조회
operation::menu-option-group/find-one[snippets='http-request,http-response,request-headers,path-parameters,response-fields']

=== 옵션 그룹 전체 조회
operation::menu-option-group/find-all[snippets='http-request,http-response,request-headers,path-parameters,response-fields']

=== 옵션 그룹 수정
operation::menu-option-group/update[snippets='http-request,http-response,request-headers,path-parameters,request-fields']

=== 옵션 그룹 삭제
operation::menu-option-group/delete[snippets='http-request,http-response,request-headers,path-parameters']

=== 옵션 그룹 메뉴 연결
operation::menu-option-group/link-menu[snippets='http-request,http-response,request-headers,path-parameters,request-fields']

=== 옵션 그룹 정렬 순서 변경
operation::menu-option-group/change-order[snippets='http-request,http-response,request-headers,path-parameters,request-fields']

[[Option]]
=== 옵션 추가
operation::menu-option-group/add-option[snippets='http-request,http-response,request-headers,path-parameters,request-fields,response-fields']

=== 옵션 조회
operation::menu-option-group/find-option[snippets='http-request,http-response,request-headers,path-parameters,response-fields']

=== 옵션 수정
operation::menu-option-group/update-option[snippets='http-request,http-response,request-headers,path-parameters,request-fields']

=== 옵션 삭제
operation::menu-option-group/delete-option[snippets='http-request,http-response,request-headers,path-parameters']

=== 옵션 정렬 순서 변경
operation::menu-option-group/change-option-order[snippets='http-request,http-response,request-headers,path-parameters,request-fields']
