[[MenuGroup-API]]
== Menu Group API

[[MenuGroup]]
=== 메뉴 그룹 추가
operation::menu-group/add[snippets='http-request,http-response,request-headers,request-fields,response-fields']

=== 메뉴 그룹 전체 조회
operation::menu-group/find-all[snippets='http-request,http-response,request-headers,path-parameters,response-fields']

=== 메뉴 그룹 단건 조회
operation::menu-group/find-one[snippets='http-request,http-response,request-headers,path-parameters,response-fields']

=== 메뉴 그룹 정보 수정
operation::menu-group/update[snippets='http-request,http-response,request-headers,path-parameters,request-fields']

=== 메뉴 그룹 메뉴 추가
operation::menu-group/add-menu[snippets='http-request,http-response,request-headers,path-parameters,request-fields,response-fields']

=== 메뉴 그룹 메뉴 조회
operation::menu-group/find-menus[snippets='http-request,http-response,request-headers,path-parameters,response-fields']

=== 메뉴 그룹 삭제
operation::menu-group/delete[snippets='http-request,http-response,request-headers,path-parameters']

=== 메뉴 그룹 메뉴 삭제
operation::menu-group/delete-menu[snippets='http-request,http-response,request-headers,path-parameters']

=== 메뉴 그룹 메뉴 순서 변경
operation::menu-group/change-menu-order[snippets='http-request,http-response,request-headers,path-parameters,request-fields']



[[Menu]]