[[Owner-API]]
== Owner API

[[Owner-join]]
=== 점주 회원가입
`POST /owner/join`

operation::owner/join[snippets='http-request,http-response,request-fields,response-fields']

[[Owner-default-login]]
=== 점주 기본 로그인
`POST /ownerLogin`

operation::owner/default/login[snippets='http-request,http-response,request-fields,response-fields,response-headers']

[[Owner-social-login]]
=== 점주 소셜 로그인
`POST /ownerLogin`

operation::owner/social/login[snippets='http-request,http-response,request-fields,response-fields,response-headers']

[[Owner-logout]]
=== 점주 로그아웃
`POST /ownerLogout/{ownerId}`

operation::owner/default/logout[snippets='http-request,http-response,request-headers,path-parameters,response-headers']

[[Owner-mypage]]
=== 점주 마이페이지 조회
`GET /owner/mypage`

operation::owner/mypage[snippets='http-request,http-response,request-headers,response-fields']

[[Owner-update]]
=== 점주정보 수정
`PATCH /owner/update`

operation::owner/update[snippets='http-request,http-response,request-headers,request-fields']

[[Owner-delete]]
=== 점주삭제
`DELETE /owner/delete`

operation::owner/delete[snippets='http-request,http-response,request-headers']