[[Shop-API]]
== Shop API

=== 입점
operation::shop/register[snippets='http-request,http-response,request-headers,request-parts']

=== 가게 정보 조회
operation::shop/get-info[snippets='http-request,http-response,path-parameters,response-fields']

=== 사장님 공지 조회
operation::shop/get-notice[snippets='http-request,http-response,path-parameters,response-fields']

=== 영업 시간 조회
operation::shop/get-business-hours[snippets='http-request,http-response,path-parameters,response-fields']

=== 배달 요금 조회
operation::shop/get-delivery-price[snippets='http-request,http-response,path-parameters,response-fields']

=== 가게 정보 수정
operation::shop/update-info[snippets='http-request,http-response,request-headers,path-parameters,request-fields']

=== 사장님 공지 수정
operation::shop/update-notice[snippets='http-request,http-response,request-headers,path-parameters,request-fields']

=== 영업 시간 수정
operation::shop/update-business-hours[snippets='http-request,http-response,request-headers,path-parameters,request-fields']

=== 배달 요금 수정
operation::shop/update-delivery-price[snippets='http-request,http-response,request-headers,path-parameters,request-fields']

=== 가게 삭제
operation::shop/delete[snippets='http-request,http-response,request-headers,path-parameters']

